# Generated by Django 5.2.4 on 2025-11-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyweightentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='calorieentry',
            name='user',
        ),
    ]
