# Generated by Django 5.2.4 on 2025-11-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_waterintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintake',
            name='amount',
            field=models.FloatField(),
        ),
    ]
