# Generated by Django 5.2.4 on 2025-11-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bodyweightentry_user_remove_calorieentry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='bodyweightentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bodyweightentry',
            name='date',
        ),
        migrations.AddField(
            model_name='bodyweightentry',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
