# Generated by Django 5.2.4 on 2025-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_meal_quickfood_alter_bodyweightentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodyweightentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20),
        ),
    ]
