# Generated by Django 5.2.4 on 2025-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_waterintake_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintake',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
