# Generated by Django 5.2.4 on 2025-11-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_waterintake_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterIntake',
        ),
    ]
