# Generated by Django 5.2.4 on 2025-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_waterintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
